services:
  db:
    image: postgres:16-alpine
    container_name: owlearning_postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: owlearning_bdd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02_seed.sql

  api:
    build: .
    container_name: owlearning_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/owlearning_bdd
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: